services:
  log_db:
    image: ath21/stls-databases:log_mongo
    container_name: log_db_container
    networks:
      - log_network

networks:
  log_network:
    name: log_network
    driver: bridge
    external: true