services:
  log_db:
    ports:
      - '27017:27017'
    env_file:
      - ../compose.log-api.secret.env  
    volumes:
      - logdb_data:/data/db
    restart: always

volumes:  
  logdb_data:
    name: logdb_data
    driver: local