services:
  user_api:
    ports:
      - '5055:8080'
    environment:
      ConnectionStrings__DefaultConnection: Server=mssql,1433;Database=UserDb;User Id=sa;Password=MyPass@word;TrustServerCertificate=True
      Jwt__Issuer: http://localhost:5055/API/User
      Jwt__Audience: http://localhost:5055/API/User
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      rabbitmq:
        condition: service_healthy
      mssql:
        condition: service_started
    networks:
      - user_network
      - rabbitmq_network
    restart: always
