services:

  user_api:
    build:
      context: .    
      dockerfile: Dockerfile
    image: ath21/stls:user_api
    container_name: user_api_container

networks:
  user_network:
    name: user_network
    driver: bridge
    external: true
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true