apiVersion: apps/v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  jwt-key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km
  connection-string: Server=mssql,1433;Database=UserDb;User Id=sa;Password=MyPass@word;TrustServerCertificate=True
  rabbitmq-username: admin
  rabbitmq-password: admin123
  