apiVersion: apps/v1
kind: Deployment
metadata:
  name: intersection-controller-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intersection-controller-api
  template:
    metadata:
      labels:
        app: intersection-controller-api
    spec:
      containers:
      - name: intersection-controller-api
        image: ath21/stls:intersection_controller_api
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        - name: Redis__TrafficLight__Host
          value: "trafficlightcachedb"
        - name: Redis__TrafficLight__Port
          value: "6379"

        - name: Redis__Detection__Host
          value: "detectioncachedb"
        - name: Redis__Detection__Port
          value: "6379"

        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: intersectioncontrollerapi-secret
              key: JWT_KEY

        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: intersectioncontrollerapi-secret
              key: RABBITMQ_USERNAME
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: intersectioncontrollerapi-secret
              key: RABBITMQ_PASSWORD

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3