apiVersion: v1
kind: Service
metadata:
  name: intersection-controller-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30190
  selector:
    app: intersection-controller-api
