services:
  notification_mongo:
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - notification_mongo_data:/data/db
    restart: always

volumes:
  notification_mongo_data:
    name: notification_mongo_data
    driver: local
