services:
  
  log_mongo:
    ports:
      - '27017:27017'
    volumes:
      - log_data:/data/db
    networks:
      - log_network
    restart: always

volumes:
  log_data:
    name: log_data
    driver: local