services:
  influxdb:
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: DetectionOrg
      DOCKER_INFLUXDB_INIT_BUCKET: DetectionDb
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: always

volumes:
  influxdb_data:
