services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_container
    networks:
      - influxdb_network

networks:
  influxdb_network:
    name: influxdb_network
    driver: bridge
    external: true
