// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficAnalyticsData;

#nullable disable

namespace TrafficAnalyticsData.Migrations
{
    [DbContext(typeof(TrafficAnalyticsDbContext))]
    [Migration("20250827213507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficAnalyticsData.Entities.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("intersection_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("AlertId");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("TrafficAnalyticsData.Entities.DailySummary", b =>
                {
                    b.Property<Guid>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("summary_id");

                    b.Property<float>("AvgSpeed")
                        .HasColumnType("real")
                        .HasColumnName("avg_speed");

                    b.Property<string>("CongestionLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("congestion_level");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("intersection_id");

                    b.Property<int>("VehicleCount")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_count");

                    b.HasKey("SummaryId");

                    b.ToTable("daily_summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
