services:
  incident_detection_api:
    ports:
      - '5109:8080' # Optional if you want metrics/health endpoints exposed
    environment:
      # ===============================
      # ASP.NET Core
      # ===============================
      ASPNETCORE_ENVIRONMENT: Development

      # ===============================
      # JWT Authentication
      # ===============================
      Jwt__Issuer: http://stls_backend:8080
      Jwt__Audience: http://stls_backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # ===============================
      # InfluxDB Connection
      # ===============================
      DetectionDb__Url: http://influxdb:8086
      DetectionDb__Token: admin-token
      DetectionDb__Org: DetectionOrg
      DetectionDb__Bucket: DetectionDb

      # ===============================
      # RabbitMQ Connection
      # ===============================
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      # ===============================
      # Exchanges
      # ===============================
      RabbitMQ__Exchanges__Sensor: SENSOR.EXCHANGE
      RabbitMQ__Exchanges__Logs: LOG.EXCHANGE


      # ===============================
      # Routing Keys (Publishes)
      # ===============================
      RabbitMQ__RoutingKeys__SensorIncidentDetected: sensor.incident.detected.{intersection_id}

      # ===============================
      # Logs
      # ===============================
      RabbitMQ__RoutingKeys__IncidentLogsAudit: log.sensor.incident_detection_service.audit
      RabbitMQ__RoutingKeys__IncidentLogsError: log.sensor.incident_detection_service.error
