services:
  log_db:
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
    volumes:
      - logdb_data:/data/db
    restart: always

volumes:
  logdb_data:
    name: logdb_data
    driver: local