apiVersion: v1
kind: Secret
metadata:
  name: detectionapi-secret
type: Opaque
stringData:
  JWT_KEY: "Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km"
  RABBITMQ_USERNAME: "rabbitmq"
  RABBITMQ_PASSWORD: "rabbitmq123"
