apiVersion: apps/v1
kind: Deployment
metadata:
  name: detectioncachedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detectioncachedb
  template:
    metadata:
      labels:
        app: detectioncachedb
    spec:
      containers:
      - name: redis
        image: redis:7.4
        command: ["redis-server", "--appendonly", "yes"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-storage
          mountPath: /data
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: detectioncachedb-pvc
