services:
  user_api:
    build:
      context: ./UserLayer/UserService/UserAPI
      dockerfile: Dockerfile
    image: ath21/stls:user_api
    container_name: user_api_container
    networks:
      - user_network
      - rabbitmq_network

  log_api:
    build:
      context: ./LogLayer/LogService/LogAPI
      dockerfile: Dockerfile
    image: ath21/stls:log_api
    container_name: log_api_container
    networks:
      - log_network
      - rabbitmq_network

networks:
  user_network:
    name: user_network
    driver: bridge
    external: true

  log_network:
    name: log_network
    driver: bridge
    external: true

  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true
