services:
  intersection_controller_api:
    image: ath21/stls:intersection_controller_api
    container_name: intersectioncontrollerapi_container
    networks:
      - traffic_light_cache_network
      - detection_cache_network
      - rabbitmq_network

networks:
  traffic_light_cache_network:
    name: traffic_light_cache_network
    driver: bridge
    external: true
  detection_cache_network:
    name: detection_cache_network
    driver: bridge
    external: true
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true
