apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationdb
  template:
    metadata:
      labels:
        app: notificationdb
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: notificationdb-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notificationdb-secret
              key: MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: notificationdb-pvc
