services:
  sensor_api:
    image: ath21/stls:sensor_api
    container_name: sensorapi_container
    networks:
      - detection_cache_network
      - detection_network
      - rabbitmq_network

networks:
  detection_cache_network:
    name: detection_cache_network
    driver: bridge
    external: true
  detection_network:
    name: detection_network
    driver: bridge
    external: true
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true
