services:
  user_db:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyPass@word
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - userdb_data:/var/opt/mssql
    restart: always

volumes:
  userdb_data:
    name: userdb_data
    driver: local
