apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30055   # access via minikube service user-api
  selector:
    app: user-api
