apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_api_container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user_api
  template:
    metadata:
      labels:
        app: user_api
    spec:
      containers:
      - name: user_api
        image: ath21/stls:user_api
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: user_service_secret
              key: connection_string
        - name: Jwt__Issuer
          value: http://localhost:5055/API/User
        - name: Jwt__Audience
          value: http://localhost:5055/API/User
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: user_service_secret
              key: jwt_key
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: RabbitMQ__Host
          value: rabbitmq
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          valueFrom:
            secretKeyRef:
              name: user_service_secret
              key: rabbimq_username
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: user_service_secret
              key: rabbitmq_password
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m" 
            
            