apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-light-controller-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-light-controller-api
  template:
    metadata:
      labels:
        app: traffic-light-controller-api
    spec:
      containers:
      - name: traffic-light-controller-api
        image: ath21/stls:traffic_light_controller_api
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        - name: Redis__TrafficLight__Host
          value: "trafficlightcachedb"
        - name: Redis__TrafficLight__Port
          value: "6379"

        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: trafficlightcontrollerapi-secret
              key: JWT_KEY

        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: trafficlightcontrollerapi-secret
              key: RABBITMQ_USERNAME
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: trafficlightcontrollerapi-secret
              key: RABBITMQ_PASSWORD
