services:
  log_api:
    ports:
      - '5005:8080'
    env_file:
      - ../compose.log-api.secret.env
    environment:
      # ===============================
      # ASP.NET Core
      # ===============================
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      # ===============================
      # MongoDB (LogDB)
      # ===============================
      Mongo__Database: LogDB
      Mongo__Collections__AuditLogs: audit_logs
      Mongo__Collections__ErrorLogs: error_logs
      Mongo__Collections__FailoverLogs: failover_logs

      # ===============================
      # CORS Policy
      # ===============================
      Cors__AllowedOrigins: http://localhost:5173,https://stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # ===============================
      # JWT Authentication
      # ===============================
      Jwt__Issuer: http://stls_backend:8080
      Jwt__Audience: http://stls_backend:8080
      # ===============================
      # RabbitMQ 
      # ===============================
      # Connection
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672

      # Exchanges, Queues, Routing Keys
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE
      RabbitMQ__Queues__Log: log.queue
      RabbitMQ__RoutingKeys__Log__0: log.sensor.#
      RabbitMQ__RoutingKeys__Log__1: log.traffic.#
      RabbitMQ__RoutingKeys__Log__2: log.user.#

    depends_on:
      log_db:
        condition: service_started
    restart: always