services:
  log-api:
    ports:
      - '5005:8080'
    environment:
      # ASP.NET Core
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SERVICE_LAYER: Log 
      SERVICE_LEVEL: Cloud
      SERVICE_NAME: Log

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://uniwa-stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://uniwa-stls-backend:8080
      Jwt__Audience: http://uniwa-stls-backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # Databases
      ## LogDB
      Mongo__ConnectionString: mongodb://mongo:mongo123@log-db:27017/
      Mongo__Database: LogDB
      Mongo__Collections__AuditLogs: audit_logs
      Mongo__Collections__ErrorLogs: error_logs
      Mongo__Collections__FailoverLogs: failover_logs

      # Message Broker
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE

      ## Queues
      RabbitMQ__Queues__Log__User: user-2-log.queue
      RabbitMQ__Queues__Log__Traffic: traffic-2-log.queue
      RabbitMQ__Queues__Log__Sensor: sensor-2-log.queue

      ## Routing Keys
      ### Consume
      RabbitMQ__RoutingKeys__Log__User: log.user.#
      RabbitMQ__RoutingKeys__Log__Traffic: log.traffic.#
      RabbitMQ__RoutingKeys__Log__Sensor: log.sensor.#

    depends_on:
      log-db:
        condition: service_started
    restart: always