services:
  traffic_analytics_db:
    image: postgres:16
    container_name: trafficanalyticsdb_container
    networks:
      - traffic_analytics_network

networks:
  traffic_analytics_network:
    name: traffic_analytics_network
    driver: bridge
    external: true
