services:
  notification-api:
    ports:
      - '5087:8080'
    environment:
      # ASP.NET Core
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SERVICE_LAYER: User Layer
      SERVICE_LEVEL: Cloud
      SERVICE_NAME: Notification Service

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://uniwa-stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://uniwa-stls-backend:8080
      Jwt__Audience: http://uniwa-stls-backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # Email (SMTP)  
      Email__SmtpServer: smtp.gmail.com
      Email__Port: 587
      Email__SenderName: UNIWA STLS
      Email__SenderEmail: ice19390005@gmail.com
      Email__Username: ice19390005@gmail.com
      Email__Password: waqr ilfj fxpu banq

      # Databases
      ## NotificationDB
      Mongo__ConnectionString: "mongodb://mongo:mongo123@notification-db:27017"
      Mongo__Database: "NotificationDB"
      Mongo__NotificationsCollection: "notifications"
      Mongo__DeliveryLogsCollection: "delivery_logs" 

      # Message Broker
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges
      RabbitMQ__Exchanges__User: USER.EXCHANGE
      RabbitMQ__Exchanges__Traffic: TRAFFIC.EXCHANGE
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE

      ## Queues
      RabbitMQ__Queues__User__NotificationRequests: requests-2-notification.queue
      RabbitMQ__Queues__Traffic__Analytics: analytics-2-notification.queue

      ## Routing Keys
      RabbitMQ__RoutingKeys__User__Notifications: user.notification.request
      RabbitMQ__RoutingKeys__Traffic__Analytics: traffic.analytics.{intersection}.{metric}
      RabbitMQ__RoutingKeys__Log__User: log.user.notification-api.{type}

    depends_on:
      notification-db:
        condition: service_started

    restart: always
