services:
  notification-api:
    ports:
      - '5087:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      # NotificationDB (MongoDB)
      Mongo__ConnectionString: mongodb://mongo:mongo123@notification-db:27017
      Mongo__Database: NotificationDB
      Mongo__NotificationsCollection: notifications
      Mongo__DeliveryLogsCollection: delivery_logs

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://stls_backend:8080
      Jwt__Audience: http://stls_backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # Email (SMTP)  
      Email__SmtpServer: smtp.gmail.com
      Email__Port: 587
      Email__SenderName: UNIWA STLS
      Email__SenderEmail: ice19390005@gmail.com
      Email__Username: ice19390005@gmail.com
      Email__Password: waqr ilfj fxpu banq

      # RabbitMQ
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges & Routing Keys
      ### User
      RabbitMQ__Exchanges__User: USER.EXCHANGE

      RabbitMQ__Queues__User__Notification: user-2-notification.queue
      RabbitMQ__RoutingKeys__UserNotifications: user.notification.{type}

      ## Traffic
      RabbitMQ__Exchanges__Traffic: TRAFFIC.EXCHANGE

      RabbitMQ__Queues__Traffic__Analytics: analytics-2-notification.queue
      RabbitMQ__RoutingKeys__TrafficAnalytics: traffic.analytics.{intersection}.{metric}

      ### Log
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE

      RabbitMQ__RoutingKeys__Log__Notification: log.user.notification-service.{type}

    depends_on:
      notification-db:
        condition: service_started

    restart: always
