services:
  traffic_analytics_api:
    image: ath21/stls:traffic_analytics_api
    container_name: traffic_analytics_api_container
    networks:
      - traffic_analytics_network
      - rabbitmq_network

networks:
  traffic_analytics_network:
    name: traffic_analytics_network
    driver: bridge
    external: true

  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true
