services:
  sensor-api-ekklisia:
    image: ath21/stls-services:sensor-api
    container_name: sensor-api-ekklisia-container
    ports:
      - '5073:8080'
    environment:
      # ASP.NET Core
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SERVICE_LAYER: Sensor 
      SERVICE_LEVEL: Fog
      SERVICE_NAME: Sensor 

      # Intersection Details
      Intersection__Id: 4
      Intersection__Name: Ekklisia

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://uniwa-stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://uniwa-stls-backend:8080
      Jwt__Audience: http://uniwa-stls-backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # Databases
      ## DetectionDB
      Mongo__ConnectionString: mongodb://mongo:mongo123@detection-db:27017
      Mongo__Database: DetectionDB
      Mongo__Collections__VehicleCount: vehicle_count
      Mongo__Collections__PedestrianCount: pedestrian_count
      Mongo__Collections__CyclistCount: cyclist_count
      Mongo__Collections__EmergencyVehicleDetections: emergency_vehicle_detections
      Mongo__Collections__PublicTransportDetections: public_transport_detections
      Mongo__Collections__IncidentDetections: incident_detections

      ## DetectionCacheDB
      Redis__Host: detection-cache-db
      Redis__Port: 6379
      Redis__Password: ""
      Redis__Database: 0
      Redis__Sensor__KeyPrefix__VehicleCount: sensor:{intersection}.vehicle_count
      Redis__Sensor__KeyPrefix__PedestrianCount: sensor:{intersection}.pedestrian_count
      Redis__Sensor__KeyPrefix__CyclistCount: sensor:{intersection}.cyclist_count
      Redis__Detection__KeyPrefix__EmergencyDetections: detection:{intersection}.emergency_vehicle_detected
      Redis__Detection__KeyPrefix__PublicTransportDetections: detection:{intersection}.public_transport_detected
      Redis__Detection__KeyPrefix__IncidentDetections: detection:{intersection}.incident_detected

      # Message Broker
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges
      RabbitMQ__Exchanges__Sensor: SENSOR.EXCHANGE
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE

      ## Routing Keys
      RabbitMQ__RoutingKeys__Sensor__Count: sensor.count.{intersection}.{count}
      RabbitMQ__RoutingKeys__Log__Sensor: log.sensor.sensor-api.{type}

    networks:
      - detection-network
      - detection-cache-network
      - rabbitmq-network

networks:
  detection-network:
    external: true
  detection-cache-network:
    external: true
  rabbitmq-network:
    external: true
