services:
  traffic_light_coordinator_postgres:
    environment:
      POSTGRES_DB: TrafficLightDb
      POSTGRES_USER: traffic
      POSTGRES_PASSWORD: traffic
    ports:
      - '5432:5432'
    volumes:
      - traffic_light_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  traffic_light_pgdata:
    name: traffic_light_pgdata
    driver: local

