services:
  traffic_light_coordinator_postgres:
    environment:
      POSTGRES_DB: TrafficLightDb
      POSTGRES_USER: traffic
      POSTGRES_PASSWORD: traffic
    volumes:
      - traffic_light_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  traffic_light_pgdata:
    name: traffic_light_pgdata
    driver: local

