services:
  user-api:
    ports:
      - '5055:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      # UserDB (MSSQL)
      ConnectionStrings__MSSQLConnection: Server=user-db,1433;Database=UserDB;User Id=sa;Password=MyPass@word;TrustServerCertificate=True

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://stls_backend:8080
      Jwt__Audience: http://stls_backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # RabbitMQ
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges & Routing Keys
      ### User
      RabbitMQ__Exchanges__User: USER.EXCHANGE

      RabbitMQ__Queues__User__Notification: notification-2-user.queue
      RabbitMQ__RoutingKeys__UserNotifications: user.notifications.{type}
      
      ### Log
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE
      
      RabbitMQ__RoutingKeys__Log__User: log.user.user-service.{type}
    
    depends_on:
      user-db:
        condition: service_started
        
    restart: always
