services:
  user-api:
    ports:
      - '5055:8080'
    environment:
      # ASP.NET Core
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://uniwa-stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://uniwa-stls-backend:8080
      Jwt__Audience: http://uniwa-stls-backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # Databases
      ## UserDB
      MSSQL__ConnectionString: Server=user-db,1433;Database=UserDB;User Id=sa;Password=MyPass@word;TrustServerCertificate=True

      # Message Broker
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges
      RabbitMQ__Exchanges__User: USER.EXCHANGE
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE

      ## Routing Keys
      RabbitMQ__RoutingKeys__User__NotificationRequests: user.notification.request
      RabbitMQ__RoutingKeys__Log__User: log.user.user-api.{type}

    depends_on:
      user-db:
        condition: service_started
        
    restart: always
