services:
  traffic-light-coordinator:
    ports:
      - '5020:8080'
    environment:
      # ASP.NET Core
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      SERVICE_LAYER: Traffic 
      SERVICE_LEVEL: Cloud
      SERVICE_NAME: TrafficLightCoordinator

      # CORS
      Cors__AllowedOrigins: http://localhost:5173,https://uniwa-stls.local
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE,OPTIONS
      Cors__AllowedHeaders: Content-Type,Authorization

      # JWT
      Jwt__Issuer: http://uniwa-stls-backend:8080
      Jwt__Audience: http://uniwa-stls-backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # Databases
      ## TrafficLightDB (MSSQL)
      ConnectionStrings__MSSQLConnection: Server=traffic-light-db,1433;Database=TrafficLightDB;User Id=sa;Password=MyPass@word;TrustServerCertificate=True;

      # Message Broker
      ## Configuration
      RabbitMQ__Host: rabbitmq
      RabbitMQ__VirtualHost: /
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      ## Exchanges
      RabbitMQ__Exchanges__Traffic: TRAFFIC.EXCHANGE
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE

      ## Queues
      RabbitMQ__Queues__Traffic__PriorityCount: priority-count-2-light-coordinator.queue
      RabbitMQ__Queues__Traffic__PriorityDetection: priority-detection-2-light-coordinator.queue
      RabbitMQ__Queues__Traffic__Analytics: analytics-2-light-coordinator.queue

      ## Routing Keys
      RabbitMQ__RoutingKeys__Traffic__PriorityCount: priority.count.{intersection}.{count}
      RabbitMQ__RoutingKeys__Traffic__PriorityDetection: priority.detection.{intersection}.{event}
      RabbitMQ__RoutingKeys__Traffic__Analytics: traffic.analytics.{intersection}.{metric}
      RabbitMQ__RoutingKeys__Traffic__LightSchedule: traffic.light.schedule.{intersection}
      RabbitMQ__RoutingKeys__Traffic__LightControl: traffic.light.control.{intersection}.{light}
      RabbitMQ__RoutingKeys__Log__Coordinator: log.traffic.light-coordinator.{type}

    depends_on:
      traffic-light-db:
        condition: service_started

    restart: always
