apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-analytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-analytics-api
  template:
    metadata:
      labels:
        app: traffic-analytics-api
    spec:
      containers:
      - name: traffic-analytics-api
        image: ath21/stls:traffic_analytics_api
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"

        # Postgres
        - name: PostgreSQL__ConnectionString
          value: "Host=trafficanalyticsdb;Port=5432;Database=TrafficAnalyticsDB;Username=postgres;Password=postgres123"

        # Redis
        - name: Redis__Host
          value: "detectioncachedb"
        - name: Redis__Port
          value: "6379"
        - name: Redis__Password
          value: ""
        - name: Redis__Database
          value: "0"

        # JWT
        - name: Jwt__Issuer
          value: "http://stls_backend:8080"
        - name: Jwt__Audience
          value: "http://stls_backend:8080"
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: trafficanalyticsapi-secret
              key: JWT_KEY

        # RabbitMQ
        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: trafficanalyticsapi-secret
              key: RABBITMQ_USERNAME
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: trafficanalyticsapi-secret
              key: RABBITMQ_PASSWORD

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3