// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficLightCoordinatorData;

#nullable disable

namespace TrafficLightCoordinatorData.Migrations
{
    [DbContext(typeof(TrafficLightCoordinatorDbContext))]
    partial class TrafficLightCoordinatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficLightCoordinatorData.Entities.Intersection", b =>
                {
                    b.Property<Guid>("IntersectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("intersection_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("Location")
                        .HasColumnType("jsonb")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("IntersectionId");

                    b.HasIndex("Status");

                    b.ToTable("intersections");
                });

            modelBuilder.Entity("TrafficLightCoordinatorData.Entities.TrafficConfiguration", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<string>("ChangeRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("change_ref");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("intersection_id");

                    b.Property<JsonDocument>("Pattern")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pattern");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("ConfigId");

                    b.HasIndex("ChangeRef")
                        .IsUnique();

                    b.HasIndex("IntersectionId", "EffectiveFrom")
                        .HasDatabaseName("ix_cfg_intersection_effective");

                    b.ToTable("traffic_configurations");
                });

            modelBuilder.Entity("TrafficLightCoordinatorData.Entities.TrafficLight", b =>
                {
                    b.Property<Guid>("LightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("light_id");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_state");

                    b.Property<Guid>("IntersectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("intersection_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(now() at time zone 'utc')");

                    b.HasKey("LightId");

                    b.HasIndex("IntersectionId", "UpdatedAt");

                    b.ToTable("traffic_lights", t =>
                        {
                            t.HasCheckConstraint("ck_traffic_lights_state", "current_state IN ('RED','ORANGE','GREEN','FLASHING','OFF')");
                        });
                });

            modelBuilder.Entity("TrafficLightCoordinatorData.Entities.TrafficConfiguration", b =>
                {
                    b.HasOne("TrafficLightCoordinatorData.Entities.Intersection", "Intersection")
                        .WithMany("Configurations")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("TrafficLightCoordinatorData.Entities.TrafficLight", b =>
                {
                    b.HasOne("TrafficLightCoordinatorData.Entities.Intersection", "Intersection")
                        .WithMany("Lights")
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");
                });

            modelBuilder.Entity("TrafficLightCoordinatorData.Entities.Intersection", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("Lights");
                });
#pragma warning restore 612, 618
        }
    }
}
