apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficanalyticsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficanalyticsdb
  template:
    metadata:
      labels:
        app: trafficanalyticsdb
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: trafficanalyticsdb-secret
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: trafficanalyticsdb-pvc
