services:
  traffic_light_control_api:
    ports:
      - '5261:8080'
    environment:
      # ===============================
      # ASP.NET Core
      # ===============================
      ASPNETCORE_ENVIRONMENT: Development

      # ===============================
      # JWT Authentication
      # ===============================
      Jwt__Issuer: http://stls_backend:8080
      Jwt__Audience: http://stls_backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # ===============================
      # Redis Connection
      # ===============================
      Redis__Host: intersection_redis
      Redis__Port: 6379
      Redis__Password: ""
      Redis__Database: 0

      # ===============================
      # RabbitMQ Connection
      # ===============================
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      # ===============================
      # Exchanges
      # ===============================
      RabbitMQ__Exchanges__Traffic: TRAFFIC.EXCHANGE
      RabbitMQ__Exchanges__Logs: LOG.EXCHANGE

      # ===============================
      # Queues (Consumes)
      # ===============================
      RabbitMQ__Queues__TrafficLightControl: traffic.light_control_service.queue

      # ===============================
      # Routing Keys (Consumes)
      # ===============================
      RabbitMQ__RoutingKeys__TrafficLightControl: traffic.light.control.{intersection_id}.{light_id}

      # ===============================
      # Logs
      # ===============================
      RabbitMQ__RoutingKeys__TrafficLogsAudit: log.traffic.light_control_service.audit
      RabbitMQ__RoutingKeys__TrafficLogsError: log.traffic.light_control_service.error

    depends_on:
      intersection_redis:
        condition: service_healthy
    restart: always
