services:
  rabbitmq:
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ../compose.rabbitmq.secret.env 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
    name: rabbitmq_data
    driver: local