services:
  rabbitmq:
    image: ath21/stls-broker:rabbitmq
    container_name: rabbitmq_container
    networks:
      - rabbitmq_network
  
networks:
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true