services:
  detection_db:
    image: mongo:6.0
    container_name: detectiondb_container
    networks:
      - detection_network

networks:
  detection_network:
    name: detection_network
    driver: bridge
    external: true