services:
  detection_api:
    ports:
      - '5122:8080'
    environment:
      # ===============================
      # ASP.NET Core
      # ===============================
      ASPNETCORE_ENVIRONMENT: Development

      # ===============================
      # Databases
      # ===============================

      ## DetectionDB (MongoDB)
      Mongo__ConnectionString: mongodb://mongo:mongo123@detection_db:27017
      Mongo__Database: DetectionDB
      Mongo__Collections__VehicleCount: vehicle_count
      Mongo__Collections__PedestrianCount: pedestrian_count
      Mongo__Collections__CyclistCount: cyclist_count
      Mongo__Collections__Emergency: emergency_vehicle
      Mongo__Collections__PublicTransport: public_transport
      Mongo__Collections__Incident: incident

      ## DetectionCacheDB (Redis)
      Redis__Host: detection_cache_redis
      Redis__Port: 6379
      Redis__Password: ""
      Redis__Database: 0
      Redis__KeyPrefix__VehicleCount: sensor:{intersection_id}:vehicle_count
      Redis__KeyPrefix__PedestrianCount: sensor:{intersection_id}:pedestrian_count
      Redis__KeyPrefix__CyclistCount: sensor:{intersection_id}:cyclist_count
      Redis__KeyPrefix__EmergencyDetected: sensor:{intersection_id}:emergency_detected
      Redis__KeyPrefix__PublicTransportDetected: sensor:{intersection_id}:public_transport_detected
      Redis__KeyPrefix__IncidentDetected: sensor:{intersection_id}:incident_detected

      # ===============================
      # CORS Policy
      # ===============================
      Cors__AllowedOrigins: http://localhost:5173
      Cors__AllowedMethods: GET,POST,PUT,PATCH,DELETE
      Cors__AllowedHeaders: Content-Type,Authorization

      # ===============================
      # JWT Authentication
      # ===============================
      Jwt__Issuer: http://stls_backend:8080
      Jwt__Audience: http://stls_backend:8080
      Jwt__Key: Nn7kLa8Rzv1XHt9UwMqP4YbFdJxVt2Km

      # ===============================
      # RabbitMQ Connection
      # ===============================
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: rabbitmq
      RabbitMQ__Password: rabbitmq123

      # ===============================
      # RabbitMQ Exchanges
      # ===============================

      ## SENSOR.EXCHANGE
      RabbitMQ__Exchanges__Sensor: SENSOR.EXCHANGE
      # --- Publish
      RabbitMQ__RoutingKeys__Sensor__EmergencyVehicle: sensor.emergency_vehicle.detected.{intersection_id}
      RabbitMQ__RoutingKeys__Sensor__PublicTransport: sensor.public_transport.detected.{intersection_id}
      RabbitMQ__RoutingKeys__Sensor__IncidentDetected: sensor.incident.detected.{intersection_id}

      ## LOG.EXCHANGE
      RabbitMQ__Exchanges__Log: LOG.EXCHANGE
      # --- Publish
      RabbitMQ__RoutingKeys__Log__Audit: log.sensor.detection_service.audit
      RabbitMQ__RoutingKeys__Log__Error: log.sensor.detection_service.error

    restart: always
