services:
  detection_api:
    image: ath21/stls:detection_api
    container_name: detectionapi_container
    networks:
      - detection_network
      - detection_cache_network
      - rabbitmq_network

networks:
  detection_network:
    name: detection_network
    driver: bridge
    external: true
  detection_cache_network:
    name: detection_cache_network
    driver: bridge
    external: true
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true
