services:
  log_api:
    ports:
      - '5005:8080'
    environment:
      DefaultConnection__ConnectionString: mongodb://mongo:27017
      DefaultConnection__DatabaseName: LogDb
      DefaultConnection__UserLogsCollectionName: Log
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      rabbitmq:
        condition: service_healthy
      log_mongo:
        condition: service_started
    networks:
      - log_network
      - rabbitmq_network
    restart: always
