services:
  log_api:
    ports:
      - '5005:8080'
    environment:
      DefaultConnection__ConnectionString: mongodb://log_mongo:27017
      DefaultConnection__DatabaseName: LogDb
      DefaultConnection__LogsCollectionName: Logs

      ASPNETCORE_ENVIRONMENT: Development

      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: admin
      RabbitMQ__Password: admin123
      RabbitMQ__Exchange: notification.exchange

      RabbitMQ__RoutingKeys__UserLogs__Error: user.logs.error
      RabbitMQ__RoutingKeys__UserLogs__Audit: user.logs.audit
      RabbitMQ__RoutingKeys__UserLogs__Info: user.logs.info
      RabbitMQ__RoutingKeys__Traffic__DailySummary: traffic.analytics.daily_summary
      RabbitMQ__RoutingKeys__Traffic__CongestionAlert: traffic.analytics.congestion_alert
      RabbitMQ__RoutingKeys__Traffic__LightControlPattern: traffic.light.control.*

    depends_on:
      log_mongo:
        condition: service_started
    networks:
      - log_network
      - rabbitmq_network
    restart: always
