services:
  notification_api:
    ports:
      - '5087:8080'
    environment:
      
      ASPNETCORE_ENVIRONMENT: Development

      # MongoDB
      DefaultConnection__ConnectionString: mongodb://notification_mongo:27017
      DefaultConnection__DatabaseName: NotificationDb
      DefaultConnection__NotificationsCollectionName: Notifications

      # RabbitMQ
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: admin
      RabbitMQ__Password: admin123
      
      RabbitMQ__UserNotificationsExchange: user.notifications.exchange
      RabbitMQ__RoutingKeys__UserNotifications__Request: user.notifications.request

      # Email settings
      EmailSettings__SmtpServer: smtp.gmail.com
      EmailSettings__Port: 587
      EmailSettings__SenderName: PADA Smart Traffic Lights System
      EmailSettings__SenderEmail: ice19390005@gmail.com
      EmailSettings__Username: ice19390005@gmail.com
      EmailSettings__Password: ezqz txge ayyf smzv
    depends_on:
      notification_mongo:
        condition: service_started
    restart: always
