services:
  user_api:
    image: ath21/stls:user_api
    container_name: userapi_container
    networks:
      - user_network
      - rabbitmq_network

networks:
  user_network:
    name: user_network
    driver: bridge
    external: true
  rabbitmq_network:
    name: rabbitmq_network
    driver: bridge
    external: true
